spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true